name: Build libcocos2dcpp.so

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y unzip build-essential

    - name: Download NDK r10e
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r10e-linux-x86_64.zip
        unzip android-ndk-r10e-linux-x86_64.zip

    - name: Set NDK
      run: echo "NDK=$PWD/android-ndk-r10e" >> $GITHUB_ENV

    - name: Build .so
      run: |
        export NDK_MODULE_PATH=$GITHUB_WORKSPACE/NarutoSenki:$GITHUB_WORKSPACE/NarutoSenki/cocos2dx:$GITHUB_WORKSPACE/NarutoSenki/external
        cd NarutoSenki/projects/NarutoSenki/proj.android-studio/app/jni
        $NDK/ndk-build V=1

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: libcocos2dcpp
        path: NarutoSenki/projects/NarutoSenki/proj.android-studio/app/libs/
