name: Build libcocos2dcpp.so

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install tools
      run: |
        sudo apt update
        sudo apt install -y unzip build-essential

    - name: Download Android NDK r21e
      run: |
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip

    - name: Set environment
      run: |
        echo "NDK=$PWD/android-ndk-r21e" >> $GITHUB_ENV
        echo "NDK_MODULE_PATH=$GITHUB_WORKSPACE/NarutoSenki:$GITHUB_WORKSPACE/NarutoSenki/cocos2dx:$GITHUB_WORKSPACE/NarutoSenki/CocosDenshion:$GITHUB_WORKSPACE/NarutoSenki/extensions:$GITHUB_WORKSPACE/NarutoSenki/external" >> $GITHUB_ENV

    - name: Debug folder (biar yakin kebaca)
      run: |
        ls NarutoSenki
        ls NarutoSenki/cocos2dx
        ls NarutoSenki/external

    - name: Build libcocos2dcpp.so
      run: |
        cd NarutoSenki/projects/NarutoSenki/proj.android-studio/app/jni
        $NDK/ndk-build V=1 -j2

    - name: Upload .so
      uses: actions/upload-artifact@v4
      with:
        name: libcocos2dcpp
        path: NarutoSenki/projects/NarutoSenki/proj.android-studio/app/obj/local/armeabi-v7a/libcocos2dcpp.so
